version: "3.7"

services:
  test:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - "./src:/app/src"
    environment:
      NODE_ENV: 'test'
  dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    command: ["yarn", "start"]
    expose:
      - "4001"
    ports:
      - "4001:4001"
    volumes:
      - "./src:/app/src"
    environment:
      PORT: 4001
      NODE_ENV: 'development'
